version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: babynames-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - babynames-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: babynames-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/app/src
    networks:
      - babynames-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: babynames-frontend
    restart: unless-stopped
    networks:
      - babynames-net

  nginx:
    image: nginx:alpine
    container_name: babynames-nginx
    restart: unless-stopped
    ports:
      - "5005:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - babynames-net

volumes:
  mongo_data:

networks:
  babynames-net:
    driver: bridge
